apiVersion: v1
kind: Service
metadata:
  name: library-app
spec:
  selector:
    app: library-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP  # Use LoadBalancer if on cloud with external access

