apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate   

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: mysql
          image: harshavardhan303/library-manager-db:1
          imagePullPolicy: IfNotPresent

          ports:
            - name: mysql
              containerPort: 3306

          envFrom:
            - secretRef:
                name: library-secrets

          resources:
            requests:
              cpu: "50m"
              memory: "512Mi"
            limits:
              cpu: "100m"
              memory: "1Gi"

          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc

